# Generated by Django 3.2.7 on 2021-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='map',
            name='mineral',
            field=models.ManyToManyField(to='mineral.Mineral', verbose_name='鉱石'),
        ),
    ]
