# Generated by Django 3.2.6 on 2021-09-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
