# Generated by Django 3.2.6 on 2021-09-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0002_remove_mineral_map'),
        ('app', '0002_auto_20210925_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='mineral',
            field=models.ManyToManyField(to='mineral.Mineral'),
        ),
    ]
