# Generated by Django 3.2.6 on 2021-08-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210828_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ヒント',
            field=models.TextField(),
        ),
    ]
