# Generated by Django 3.2.6 on 2021-08-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_post_ヒント'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='作成者',
            new_name='author',
        ),
    ]
