# Generated by Django 3.2.6 on 2021-08-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210831_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='hint',
            field=models.TextField(verbose_name='ヒント'),
        ),
        migrations.AlterField(
            model_name='map',
            name='place',
            field=models.CharField(max_length=200, verbose_name='場所'),
        ),
    ]
