# Generated by Django 3.2.6 on 2021-09-06 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
