# Generated by Django 3.2.6 on 2021-09-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210928_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.image'),
        ),
    ]
