# Generated by Django 3.2.6 on 2021-09-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210906_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
