# Generated by Django 3.2.6 on 2021-09-28 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
