# Generated by Django 2.0.2 on 2021-09-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210916_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='map',
            name='published_date',
        ),
    ]
