# Generated by Django 3.2.6 on 2021-09-20 11:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('app', '0013_auto_20210919_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='tag',
        ),
        migrations.AddField(
            model_name='map',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='タグ'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
