# Generated by Django 3.2.7 on 2021-10-23 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=30, verbose_name='コメント')),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('menber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teamid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_id', to='accounts.team')),
            ],
        ),
    ]
