# Generated by Django 3.2.7 on 2021-10-23 14:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_teamchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamchat',
            name='menber',
        ),
        migrations.AddField(
            model_name='teamchat',
            name='author',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
