# Generated by Django 3.2.7 on 2021-10-07 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='text',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='紹介文'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(max_length=100, verbose_name='チーム名'),
        ),
    ]
