# Generated by Django 3.2.6 on 2021-10-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teamchat_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamchat',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
