# Generated by Django 3.2.6 on 2021-10-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teamchat_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamchat',
            old_name='published_date',
            new_name='published_at',
        ),
    ]
