# Generated by Django 3.2.7 on 2021-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_published_date_teamchat_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchat',
            name='text',
            field=models.CharField(max_length=100, verbose_name='コメント'),
        ),
    ]
