# Generated by Django 3.2.7 on 2021-11-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_teamchat_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamchat',
            name='text',
            field=models.TextField(max_length=100, verbose_name='コメント'),
        ),
    ]
