# Generated by Django 3.2.6 on 2021-09-25 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mineral',
            name='map',
        ),
    ]
