# Generated by Django 2.0.2 on 2021-09-16 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mineral', '0002_auto_20210916_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mineral',
            name='published_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
