# Generated by Django 3.2.6 on 2021-09-20 11:04

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('mineral', '0004_alter_mineral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
